# Generated by Django 5.1.1 on 2024-09-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_appointment_patient_appointment_patient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='app_id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
